//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD.GA.BE.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulo()
        {
            this.Documento_Articulo = new HashSet<Documento_Articulo>();
        }
    
        public int Id_Articulo { get; set; }
        public string Descripcion { get; set; }
        public double Stock { get; set; }
        public string Moneda { get; set; }
        public decimal Costo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int Id_Area { get; set; }
        public int Id_UnidadMedida { get; set; }
        public string Estado { get; set; }
        public Nullable<double> CantidadMinima { get; set; }
        public string Marca { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documento_Articulo> Documento_Articulo { get; set; }
    }
}
