//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD.GA.BE.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento_Articulo
    {
        public int Id_DocumentoArticulo { get; set; }
        public int Id_Articulo { get; set; }
        public int Id_Documento { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public string RazonSocial { get; set; }
        public string RUC { get; set; }
        public string DescripcionArticulo { get; set; }
        public string CodArea { get; set; }
        public string UnidadMedida { get; set; }
        public double Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<int> Id_Proveedor { get; set; }
        public string RazonSocialProveedor { get; set; }
        public string RUCProveedor { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string NombreArea { get; set; }
        public string TelefonoProveedor { get; set; }
        public string NombreBanco { get; set; }
        public string CuentaBanco { get; set; }
        public string TipoCuentaBanco { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Documento Documento { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
